### PR TITLE
Weather updates are now corrected!

### PR DESCRIPTION
**Pull request by paytime**
Weather updates are now send to all players in the zone instead of the first found player (and all nearby).

### CODE REVIEW

**Comment by thepparker** [comment]
Tabs

**Comment by paytime** [comment]
It looked well formatted in VS 😭

**Comment by GuybrushGit** [comment]
Tools->Options->Text Editor->All Languages->Tabs->Insert Spaces

**Comment by StadenElysium** [comment]
This was already fixed in the core but apparently somehow went missing in the transition to GitHub. Will add the original fix shortly.

**Pull request closed without merging**
