### PR TITLE
Proposal fix for Herod's savage Myrmidons spawn on aggro

### PR DESCRIPTION
**Pull request by sipertruk**
~~The spawn happens now only when Herod's target exits his room.
They despawn on Herod's reset, they don't despawn on his death and still drop nothing.~~
The spawn happens now at the opposite side of the corridor before the room.
They will engage a player coming close or Herod's target when he exits his room, running toward it.
They always despawn on Herod's reset, they despawn on his death only if they have no target, they drop the usual stuff.

I couldn't find any problem with the door and lever.

Related reports and duplicate
Issue #65
https://elysium-project.org/bugtracker/issue/2700
https://elysium-project.org/bugtracker/issue/3900
https://elysium-project.org/bugtracker/issue/3732
https://elysium-project.org/bugtracker/issue/2950

### CODE REVIEW

**Comment by FractalCabush** [comment]
Nice! However its not when the target leaves the room but when herod leaves the room ( following his target ofc) that they should spawn :)

**Comment by m-laniakea** [comment]
Good. Line 171, just change that to `!m_creature->IsWithinDist2d(RoomCenter.x, RoomCenter.y, 32.0f)`. Perhaps give a bit more leeway as well, as distance calculations are not guaranteed to be accurate.

**Comment by sipertruk** [comment]
Is it to ensure a safer result of IsWithinDist2d or do you have precise info ?
If the player exits the room and run down the corridor they would spawn behind him coming from nowhere, it's a less rational event.
In fact we better spawn them at the other end of the corridor, make them wait and aggro only when herod exits or despawn on his death/reset.
That would fit what is said here, just found it, but it's from 2007 : http://wowwiki.wikia.com/wiki/Talk:Herod

**Comment by sipertruk** [comment]
Updated my 1st comment, maybe 32.0f is fine, it's already a bit further than any place in the room.

**Comment by Unknown-as-Captain** [comment]
Seems to fix everything that was wrong in the fight, I love this.

We might never get 100% certain details of what the "blizzlike" behavior was, but given the incredible obscurity of this anti-kiting feature (that 99% of people won't even see, ever) this is a working, more-than-acceptable implementation.

What's important is that the door isn't important anymore, and that the adds shouldn't even be noticed by the players unless they run out to the hallway. This fix does that perfectly.

**Pull request merged**
