### PR TITLE
CompareAuraRanks should compare more effects

### PR DESCRIPTION
**Pull request by sipertruk**
Some spells have ranks with the same base value in the first effects.
Example Frost Shock :
image

### CODE REVIEW

**Comment by thepparker** [comment]
What does this achieve?

**Comment by sipertruk** [comment]
Better comparison between aura ranks every time this function is used. 6 times in the core currently.

**Comment by sipertruk** [comment]
If you need a real example :
PlayerControlledAI is building a list of the player's abilities with only highest ranks, lower ranks are left in that list because of that bug.

**Comment by thepparker** [comment]
Cool, was just wondering what it addressed

**Comment by sipertruk** [comment]
But then I just realize it would have side effects in the aura incredible machine.
Nevermind PlayerControlledAI needs more something like CompareSpellRanks.

**Pull request closed without merging**
