### PR TITLE
Fix Wrath of Cenarius proc.

### PR DESCRIPTION
**Pull request by brotalnia**
Fixes issues https://github.com/elysium-project/server/issues/420, https://github.com/elysium-project/server/issues/2564, https://github.com/elysium-project/server/issues/2706.

This makes it so Wrath of Cenarius has a chance to proc every time consecration, arcane missiles or judgement deals damage. There is probably a much better way to fix it though. Its most likely a problem with how PROC_FLAG_SUCCESSFUL_NEGATIVE_SPELL_HIT works. I think those spells are supposed to have a chance to proc whenever any negative magical effect lands on a target.

If you search for spells with the same procflag as Wrath of Cenarius, you can see their descriptions support this:

> Mystical Disjunction
> Gives a chance **when your harmful spells land** to reduce the magical resistances of your spell targets by $25768s1 for $25768d.

> Engulfing Shadows
> Chance on **landing a damaging spell** to deal $27860s1 Shadow damage and restore $27860s2 mana to you.

### CODE REVIEW

**Comment by connormcgregor** [comment]
@brotalnia also it should proc on every consecration tick since consectration is an aoe spell.
It should proc once on direct spells and only on the first tick of a DoT and procs on every tick of arcane missiles

**Comment by Mostprovidedlinks** [comment]
Brotalnia is the best person on elysium.

All cheers to brotalnia. Hip hip hooray

Hip hip hooray! Hip hip hooray!

Thanks for fixing this. I guess now I have to let you what happened to me in that black drake video. A promise is a promise. I kept you hanging on suspense. Sadly I should of had insignia on. And my bubble was on cd. But lay on hands was on 8 seconds and I died. That part pissed me off.

**Comment by Mostprovidedlinks** [comment]
@brotalnia Brotalnia is the best person on elysium.

All cheers to brotalnia. Hip hip hooray

Hip hip hooray! Hip hip hooray!

Thanks for fixing this. I guess now I have to let you what happened to me in that black drake video. A promise is a promise. I kept you hanging on suspense. Sadly I should of had insignia on. And my bubble was on cd. But lay on hands was on 8 seconds and I died. That part pissed me off.

Yeah sorry to disappoint  I didnt win. I prefer to be honest than not.

**Comment by Mostprovidedlinks** [comment]
@brotalnia Brotalnia is the best person on elysium.

All cheers to brotalnia. Hip hip hooray

Hip hip hooray! Hip hip hooray!

Thanks for fixing this. I guess now I have to let you what happened to me in that black drake video. A promise is a promise. I kept you hanging on suspense. Sadly I should of had insignia on. And my bubble was on cd. But lay on hands was on 8 seconds and I died. That part pissed me off.

Sorry to disappoint.

**Comment by brotalnia** [comment]
Okay so now it can proc when:
- Consecration or other AoE spell deals damage.
- Channeled spell like Arcane Missiles deals damage.
- Direct damage spells like Judgement.
- Putting a debuff on the target.

It cannot proc when a debuff ticks.

**Comment by Mostprovidedlinks** [comment]
@brotalnia you are the best

**Comment by Itembugs** [comment]
@brotalnia did you make it so its affected by the spell from storm gauntlets and fiery plate gauntlets?

**Comment by brotalnia** [comment]
I have no idea, have not tried that. I fixed it to proc in the circumstances i described above.

**Pull request merged**
