### PR TITLE
Limit unit tracking visibility to the caster

### PR DESCRIPTION
**Pull request by WobLight**
This fixes https://github.com/elysium-project/server/issues/977
It's so bad it's almost an hack, but there's no other way afaict.

### CODE REVIEW

**Comment by thepparker** [comment]
I'm pretty sure the hunter's party should see the tracking from hunter's mark

**Comment by WobLight** [comment]
Unfortunately it's very hard to find videos about that, the only one I've found it's this one:
https://youtu.be/HxfN9f88P0I?t=28
You can see there's a hunter in the player's party and the target is marked, yet nothing is shown on the minimap. Of course it could be a mark of another hunter, but I can't find a better video. There was one with world PvP and and hunter in party, but the marked one was near the player so the minimap dot might have been overlapped.

**Comment by WobLight** [comment]
collected one more
https://youtu.be/2bIvcPRkoUI?t=10
https://youtu.be/2bIvcPRkoUI?t=233

**Comment by thepparker** [comment]
Ok, well 3:48 confirms it then. Only visible for the hunter (or hunters?)

**Pull request merged**
