### PR TITLE
Fixed Hillsbrad foothils lions and Skeletons - Patch #2 added consistency.

### PR DESCRIPTION
**Pull request by Tenarie**
Mountain Lions in Hillsbrad foothills will no longer be stealthed
Skeletons now only immune to the following
---------------
Now only immune to
Charm
Fear
Sleep
Bleed
Polymorph
Banish

### CODE REVIEW

**Comment by QAkvastskaft** [comment]
I'm no expert but will not your fix for the skeleton issue result in mobs that currently (Correctly) have the same immunities as the skeletons (incorrectly) also be swapped to the same immunites as the skeletons?

**Comment by Tenarie** [comment]
try to querry it, it's only skeletons who has that mask. like 42 npc's.
It fits perfectly.

**Comment by QAkvastskaft** [comment]
No further questions :)

**Comment by m-laniakea** [comment]
`world` is not quite correct. People might have a differently-named database.

**Comment by m-laniakea** [comment]
Ok, now it's missing \`backticks\`, **semicolons (;)** at the end of statements, and a consistent style. `creature_id` is capitalized. Please have things like UPDATE and DELETE either all small or all large. 
Maybe have a look at #76.

**Comment by Tenarie** [comment]
Fixed.

**Comment by m-laniakea** [comment]
Thank you, Tenarie.

image

**Pull request merged**
