### PR TITLE
Error Wars 3 - Revenge of the Fix

### PR DESCRIPTION
**Pull request by brotalnia**
Behold! The god migration is here! The error fix of your dreams! The one that will bring balance to the force! The Frodo for your Sauron! The Harry Potter for your Voldemort!

Silly talk aside, this is a pull requests that fixes all database errors. I have gone through the startup errors line by line, and meticulously fixed each one. There are comments in the sql file, but here is a short summary of the errors.

- Table `item_template` - 1 error.

- Table `creature` - 226 errors.
Lots of errors but easy to fix. The health or mana of some creatures was changed in `creature_template` but their current health wasn't updated in this table. Also a bunch of errors due to spawns created with .npc spawn command in game. When you use the command it sets the `spawndist` column to 5, but that produces an error when MovementType is not set to random movement.

- Table `creature_addon` - 39 errors.
Orphaned entries. Some creature spawns were deleted from `creature` but not from this table.

- Table `quest_template` - 62 errors. 
Most errors were due to some quests having a reward/source item id, but the item count wasn't specified. Also a bunch of errors caused by old custom quests, which i removed.

- Table `creature_questrelation` - 4 errors.

- Table `creature_involvedrelation` - 3 errors.

- Table `game_event_gameobject` - 164 errors.
A bunch of gameobjects from 2 pools (166 and 168) were either added for the wrong event, or parts of the pool weren't listed for the event.

- Table `condition` - 1 error.
There was a condition for a non existing event. The condition was only used for Talisman of the Binding Shard in `creature_loot_template`. Most likely it was used to control whether the talisman can drop on Nostalrius, but the event was deleted at some point.

- Table `scripted_event_id`- 1 error.

- Table `game_graveyard_zone` - 1 error.

- Table `spell_target_position` - 4 errors.

- Table `spell_affect` - 8 errors.

- Table `creature_loot_template` - 69 errors.
Some items didn't have a drop chance specified, some creatures had loot when they shouldn't drop anything according to wowhead comments, while others didn't have their loot id assigned.

- Table `fishing_loot_template` - 1 error.

- Table `gameobject_loot_template` - 3 errors.

- Table `pickpocketing_loot_template` - 1 error.

- Table `skinning_loot_template` - 10 errors.

- Table `reference_loot_template` - 1889 errors.
The big one. Most were about unused reference loot templates, and the rest were about errors in the unused templates. I removed the unreferenced loot templates since all they do is produce errors.

- Table `npc_vendor` - 1 error.

- Table `creature_movement_scripts` - 6 error.

- Table `creature_movement` - 99 errors.
Some duplicated waypoints for creatures that have a different GUID now, some waypoints using a non-existent movement script, some creatures with waypoints not having MovementType set to waypoint.

- Table `creature_movement_template` - 99 errors.
The same like the other waypoints table. These took a long time to fix.

- Tables `battleground_events` - 14 errors.
A bunch of events with no data at all, and other events referencing non-existent gameobject or creature guids.

- Table `creature_battleground` - 19 errors.

- Table `gameobject_battleground` - 4 errors.

- Table `quest_start_scripts` - 1 error.

- Table `quest_end_scripts` - 29 errors.

- Table `spell_scripts` - 3 errors. 

- Table `gameobject_scripts` - 4 errors.

- Table `event_scripts` - 32 errors.
Most of the errors here were caused by the fact that database spell data was not taken into account when checking if the event id is used. I updated ScriptMgr to fix that.

- Table `db_script_string` - 47 errors.

- Tables `creature_ai_scripts` - 56 errors.
Mostly generic errors that are easy to fix, like an event having a 0 chance, repeatable events with no timers, or having the wrong flags set.

- Table `creature_ai_texts` - 120 errors.
Surprisingly, those took the longest to fix, since they cannot be fixed in bulk. First had to figure out what the text is for, then add it to the correct table and finally update the scripts that use them.

- Table `creature_ai_summons` - 4 errors.

- Table `script_texts` - 3 errors.

- Table `spell_disabled` - 1 error.

In total about 3011 startup errors have been fixed. I also fixed a few minor bugs that i noticed while working on some of the startup errors, like missing waypoints or texts. Now we can finally see when new errors are introduced, and judge those responsible accordingly. :hammer: 

Enjoy an error-free console.

### CODE REVIEW

**Comment by brotalnia** [comment]
I forgot to mention that i fixed some of the startup errors in separate pull requests:
https://github.com/elysium-project/server/pull/1590
https://github.com/elysium-project/server/pull/1646
https://github.com/elysium-project/server/pull/1669
https://github.com/elysium-project/server/pull/1693
https://github.com/elysium-project/server/pull/1744

Once those are merged too, there will be literally just 8 errors left.

> ERROR:`spell_bonus_data` entry for spell 348 `direct_bonus` not needed (data from table: 0.207790, calculated 0.207714, difference of 0.000076) and 
> ERROR:                                  ... `dot_bonus` not needed (data from table: 0.127270, calculated 0.127257, difference of 0.000013)
> ERROR:`spell_bonus_data` entry for spell 26573 `dot_bonus` not needed (data from table: 0.041600, calculated 0.044444, difference of 0.002844) and direct also not used

Those are not really errors, just letting you know the difference is really small.

> ERROR:Spell 25918 listed in `spell_threat` as custom rank has same data as Rank 1, so redundant

This one shouldn't exist, there is no entry 25918 in that table. Anyone have any ideas?

> ERROR:No script found for ScriptName 'boss_fugen'.
> ERROR:No script found for ScriptName 'boss_grobbulus'.
> ERROR:No script found for ScriptName 'boss_stalagg'.
> ERROR:No script found for ScriptName 'boss_thaddius'.

These will be fixed once Naxxramas is merged with this repository.

**Comment by Schmoha** [comment]
Hello, since its not possible to PM on github, i wanted to ask you if you were interested in fixing stuff in AV, there are several bugs nobody knows and cares about, finding you, your dedication on fixing bugs for Elysium, i thought i wanna ask you here for a bugreport that i made for AV, and if you were interested in fixing it, its not much, just deleting NPC's:  https://github.com/slackapi/hubot-slack/issues/16#issuecomment-35176711

**Comment by brotalnia** [comment]
@Schmoha As you mentioned in your bug report, those NPCs were placed there intentionally by Nostalrius. So it's matter of custom content, not simply bugs. You would have to discuss this with members of the staff and have them agree to remove the custom npc placement. The issue is not comparable to the errors fixed in this pull request, as this fixes literal errors. Bugs introduced by mistake, not design decision.

**Comment by Schmoha** [comment]
How should i discuss with them ? Elysium topic ? Forum ? 

So you cant just remove them? I mean Elysium goes for blizzlike and this is not blizzlike. I mean right now anyone on the Staff can just add any npc they want and it cant get fixed from the github ? Well anyway, im gonna see what i can do, could you not talk to them ?

**Comment by Phoosy** [comment]
Make a new Issue with your findings - no one on staff can just 'add' whatever they want, this is not how the set up is designed. The Core contains remnants of changes from Nostalrius's days and some things have persisted since then. If something is implemented that you believe is incorrect or not valid then that is what the Github is for.

**Comment by Schmoha** [comment]
Hi, Phoosy. So yea thats what i did, i created an topic on github, containing everything needed. Its something that is wrong and yea, what can i do ? Devs are here... I am not activly playing on this server, and nobody is interested in this and just playing by believing all they see is vanilla while it is custom. Im here to help, this issue is in my head since Nostalrius added them. why cant anyone remove that ? Reported this on Elysiums own bugtracker on their website and well i forgot what the Staff member said but that was that, nothing more to give... where is the dedication for "Blizzlike" status ?? That custom implementation which is invalid is so obvious.

**Comment by Phoosy** [comment]
The Bugtracker on the website is not where Elysium's dev team keeps track of issues; this Github is. Personal crusade issues aside, you've done your piece so there's nothing more that needs to be said about it.

**Comment by Lisbuxx** [comment]
What about Arathi basing / Warsong gulch / Alterac Valley Mark turn ins being broken on Darrowshire. The repeatable quest works just fine but the actual intial first quest is broken and doesn't excist or work. People who have never pvp'd cannot turn in marks if they start it now. There are rankers that are unable to compete currently with the rest cause of this bug. Should be quite high priority fix even when we are a PvE server.

**Comment by berillis** [comment]
https://github.com/elysium-project/server/pull/1979: A fix for the BG marks.

**Pull request merged**
