### PR TITLE
Make general channels multi-language v2

### PR DESCRIPTION
**Pull request by Neo2003**
Now compile properly on Windows AND Linux.
I dropped honor part for now so that gcc is happy.

Neo2003

### CODE REVIEW

**Comment by Neo2003** [comment]
I have Defense channel requirements coded and working on both Windows and Linux, but since it depends on this one, I will open a PR for it when this one is merged.

**Comment by m-laniakea** [comment]
The general channels were changed specifically not to be multi-language.
We want English to be spoken in general, major cities, etc.

People are free to communicate in whatever language they wish in private or in guild chat.

**Comment by Neo2003** [comment]
I understand, but from non English client, we can't talk nor read what is written in general channels because the channels have not the same name. The purpose of this patch is to enable from any language client to read/talk in these channels. After, for me it's a question of server rules to enforce the use of English only on general channels which seams obvious.

**Comment by StadenElysium** [comment]
Reverted due to major performance issues that require investigation.

**Comment by ryancheung** [comment]
😅

**Pull request merged**
