### PR TITLE
Fix for sweeping strike with execute

### PR DESCRIPTION
**Pull request by Tenarie**
The current sweeping strike just makes an AA.

https://elysium-project.org/bugtracker/issue/604

### CODE REVIEW

**Comment by sidsukana** [comment]
What about Execute? There is no check of 20% HP.

**Comment by Tenarie** [comment]
Looking into it :), thought we were going for 1.9 patch notes.
But i've read that spells and talents should follow 1.12 : ).

**Comment by Tenarie** [comment]
Ay, i'd like to hear what you think.
I think it's pretty spot on to the real vanilla.

**Comment by m-laniakea** [comment]
Reopen

**Pull request merged**
