### PR TITLE
Shield Bash should not trigger main hand

### PR DESCRIPTION
**Pull request by Yoshgit**
Addressing #1023

Proof:
http://eu.battle.net/wow/en/game/patch-notes/2-0-1
"BUGS: Warrior "Shield Slam" and "Shield Bash" will no longer trigger a proc from an equipped weapon."

### CODE REVIEW

**Comment by robmonte** [comment]
Why was this merged? The patch notes linked clearly show patch 2.0.1? Am I missing something?

**Comment by Yoshgit** [comment]
It was labeled as a bug. It was never intended to proc main hand weapons.

**Comment by robmonte** [comment]
There are many other bugged mechanics that are fixed in later patches that were left in the server on purpose because that's how they actually were in vanilla. Wasn't that the goal, to me as true to the real blizzard vanilla experience as possible?

**Comment by Yoshgit** [comment]
I'm not related to the QA team in any way, but think the QA team follows the philosophy of not reproducing bugs, whether they happened in vanilla or not.

**Comment by robmonte** [comment]
Interesting. I wonder when the stance changed on this? Because I'm pretty sure I remember them being in favor of leaving in vanilla bugs.

**Pull request merged**
