### PR TITLE
Implemented the Warchief's Blessing event

### PR DESCRIPTION
**Pull request by GuybrushGit**
https://elysium-project.org/bugtracker/issue/1200
Aditional sources:
https://www.reddit.com/r/wow/comments/1sob6t/people_which_only_play_one_faction_talk_to_me/cdzqh4s/
http://wowwiki.wikia.com/wiki/Herald_of_Thrall

Event behaviour:

When turning in the quest a Herald of Thrall is spawned on the Crossroads.
2 secs later he and Thrall yell _Honor your heroes! On this day, they have dealt a great blow against one of our most hated enemies! The false Warchief, Rend Blackhand, has fallen!_
10 secs later Thrall yells _Be bathed in my power! Drink in my might! Battle for the glory of the Horde!_ and the Herald yells _Be bathed in the power of the Warchief! Drink in his might! Battle for the glory of the Horde!_
2 secs later both cast the Warchief's Blessing.
The buff also goes out to the rest of Orgrimmar, Razor Hill and Camp Taraujo.

I could find no video recordings so the timers are an approximation.

### CODE REVIEW

**Comment by Slicy** [comment]
The buff should be on a 6 hours cooldown. 
http://wow.allakhazam.com/forum.html?forum=21&mid=113690196285182144

**Comment by PlaskED** [comment]
Is there any info other than reddit/wowwiki? I mean it existed no doubt but some facts are questionable

**Comment by PlaskED** [comment]
Nvm saw bugreport

**Comment by GuybrushGit** [comment]
Added the 6 hour cooldown. Do you know if the Herald stays there for the whole 6 hours?

**Comment by Slicy** [comment]
I don't no. The best info I could find about it was this ZAM thread.

**Comment by Slicy** [comment]
- Did not work in Camp Taurajo (0 npcs got the buff)
- Event is missing at The Crossroads (what is under : "static const SpawnLocation aBlessingGeneratorLocs[8]" should also have The Crossroads in it and it should become [9])
- Worked in Orgrimmar and Razor Hill

I do not know whether or not the Heralds spawned in the locations (both in working and non working cases).

**Comment by knasen88** [comment]
If you are gonna put a cooldown on this you better put a cooldown on onyxia head buff aswell. Not only is it rare and hard to coordinate somebody turning in a chain at your raidtime, it even has a ICD and becomes wasted half the time. Absurd

**Comment by knasen88** [comment]
Also that "Zam" source is ZERO credible proof of there being an actual cooldown for it, you have to remember high pop server in vanilla was 1,5k to 2k online and the amount of people completing that quest A DAY is probably no more than 1-2. 

One guy says "once a day" one guy says "6 hours" meanwhile others say until the summoned guy despawns. That this kangaroo court decides a swift 6 hours based on ONE post is ridiculous

**Comment by PlaskED** [comment]
Well, Onyxia and Nefarian buff also supposedly have a 6 hour cooldown so it's not entirely far fetched.

**Comment by Slicy** [comment]
Did you even read the thread ? Several occurrences of different players indicating that it's at least on a 6 hours CD and confirmed happening once or twice a day depending on retail realms.
Come up with more reliable sources proving it does not have a CD instead of ranting randomly, linking a custom server's vanilla database and wowiki links anybody can edit.

Please explain why your opinion would be more credible/relevant than comments of several different players from 2006 ? 

I'll just leave this here since you seem to complain about the difficulty of getting the buff : 
_"So you go to turn in the head of Rend.. unless there was someone in your guild that was on and in Orgrimmar ALL DAY AND NIGHT to know when the last Blessing was, you'd be going in blind on the turn-in and hoping to get the buff. "_ - Jan 10 2006 at 9:20 AM

You haven't dug anything at all concerning the event. You just talk about completely different ones.

**Comment by knasen88** [comment]
https://web.archive.org/web/20070602172347/http://www.worldofwarcraft.com/patchnotes/patch-05-09-13.html
Proving the Rallying Cry of the Dragonslayer Cooldown.

Now, that same guy "verifying" that it's 6 hours cooldown also say it's an 2 hour buff and Rallying cry is 1 hour. He certainly seems like a solid choice to trust in this case. 

Why I am bringing Ony/Nef buff into this is because I get the feeling if alliance also would be cucked on their worldbuffs there is suddenly no need to go full blizzlike.

**Comment by knasen88** [comment]
Requesting reopening of this, the evidence of a 6 hour cooldown looks like the biggest cangaroo court i've ever seen. @StadenElysium @GuybrushGit 

quoting @tunesisback back on #1529 

> http://wow.allakhazam.com/forum.html?forum=21&mid=113690196285182144#3

>>I'm not positive but I think the buff can't go off every hour. I think it can only be given by Thrall once every 6 hours.

"I think" isn't evidence of anything.

>http://wow.allakhazam.com/forum.html?forum=21&mid=113690196285182144#10

>edit: It's too hard to time when you get the buff. It's either once a day or every 6 hours (the 6 hour one is correct I'm thinking now..).
This commenter only says 6 hours because someone earlier in the thread said so. This commenter wasn't sure if it was every 24h or every 6h, a HUGE difference that would easily be confirmable if the player had any idea what they were talking about.

Further down in the same post (number 10)

>Can you really get thru to Rag or Nef in 2 hours after being in Org with your whole raid? Some guilds could, but doubtful...
This raises some questions. MC in over 2h? I wouldn't include this poster in the top tier of player from that era, so I begin to doubt whether or not they would be acutely aware of the buff timers.

http://wow.allakhazam.com/forum.html?forum=21&mid=113690196285182144&h=50&p=1#16

>Yeah..6 hours seems accurate. On azshara we get it about twice a day every day.
Again, it's just the same kind of language. "seems, about" are qualifying words. I don't doubt there was a cooldown, i just have't seen anything in these sources that convinces me it's six hours.

However, again, this ends up beside my point earlier.

Elysium is not strictly or objectively a blizzlike server. There have already been a great deal of non-blizzlike deviations. Even if the buff can be strongly proved to have such a long cooldown, given the high population, it would be a grave mistake to implement it.

Just delete the CD okay

**Comment by knasen88** [comment]
can you fucking remove this 6 hour CD (which infact is way longer than 6 hours since it is bugged) that HAD NO REAL SOURCE FROM THE START? DOES ALL GMS PLAY ALLIANCE?

zero credible "proof"

**Pull request merged**
