### PR TITLE
Compile fix

### PR DESCRIPTION
**Pull request by Thetruecrow**
Lots of changes, removed singleton call from vmap removing the use for including world header breaking vmap assembler building.

c/p of commit messages:
Fixed compile errors when building with tools.
Added actual extractors to project when extractors are enabled.
Fixed compile for ad, vmapextractor, vmap_assembler, mmap.
Restructured library usage of libmpq and loadlib.

### CODE REVIEW

**Comment by Itzamnaaj** [comment]
Thanks for your work on the extractors. However, compilation still fails on Linux with the following errors:

`/home/itzamna/src/elysium-server/contrib/vmap_extractor/vmapextract/adtfile.h:22:31: fatal error: libmpq\mpq_libmpq.h: No such file or directory`

`/home/itzamna/src/elysium-server/contrib/vmap_extractor/vmapextract/dbcfile.cpp:20:31: fatal error: libmpq\mpq_libmpq.h: No such file or directory`

`/home/itzamna/src/elysium-server/contrib/extractor/dbcfile.cpp:22:31: fatal error: libmpq\mpq_libmpq.h: No such file or directory`

`/home/itzamna/src/elysium-server/contrib/vmap_extractor/vmapextract/model.cpp:23:29: fatal error: loadlib\loadlib.h: No such file or directory`

`/home/itzamna/src/elysium-server/contrib/extractor/System.cpp:33:31: fatal error: libmpq\mpq_libmpq.h: No such file or directory`

`/home/itzamna/src/elysium-server/contrib/mmap/src/../../../src/game/Maps/MoveMapSharedDefines.h:23:62: fatal error: ../recastnavigation/Detour/Include/DetourNavMesh.h: No such file or directory`

I got the tools to compile with trivial adjustments of the CMakeLists, I'll clean them up and submit a pull request over the weekend.

**Comment by Ituury** [comment]
@Itzamnaaj Exactly the same error on Linux Arch. Looking forward for the fix.

**Comment by Thetruecrow** [comment]
Linux fix pending, currently there is code on server/Giperionn that I am investigating as well. That branch should be able to be fully compiled regardless of OS but I have not checked myself.

**Comment by Ituury** [comment]
Tried it on Windows doesn't seems to work with the branch Giperionn, get the following error
 - `LINK : fatal error LNK1104: cannot open file 'libmpq.lib`
- `Done building project "vmapextractor.vcxproj" -- FAILED.`

**Comment by Itzamnaaj** [comment]
I have an outstanding pull request (https://github.com/elysium-project/server/pull/990) that fixes compilation of the tools on GNU/Linux.

There were many oopsies in the CMake build system and the code itself, but the most perplexing was the use of backslashes ("\\") in include paths inside source files.

Please do remember that this doesn't fix the vmap / mmap version mismatch between the tools and the server, that fix is forthcoming.

**Pull request merged**
