### PR TITLE
Fixed miscellaneous world db errors

### PR DESCRIPTION
**Pull request by brotalnia**
I fixed some of the database errors when starting the server.

### CODE REVIEW

**Comment by iNDRLM** [comment]
nice work brotalnia, I was waiting for some input from Elysium/sheena about a proper DB but I guess we will be just slowly configuring Stock mangos to work with the core.
Ill go through script names when I get home and match them up with DB entries.

**Comment by brotalnia** [comment]
I did some of that too, but i didn't include it in the pull request cause i wasn't sure if they are not using the scripts of purpose. Maybe they are badly done or something? Would be nice if some of the staff can comment on the whole database situation.

```
-- ERROR:Script registering but ScriptName npc_AlteracDardosh is not assigned in database. Script will not be used.
UPDATE creature_template SET ScriptName="npc_AlteracDardosh" WHERE entry=13140;
-- ERROR:Script registering but ScriptName zero_Mob_Grethok_The_Controller is not assigned in database. Script will not be used.
UPDATE creature_template SET ScriptName="zero_Mob_Grethok_The_Controller" WHERE entry=12557;
-- ERROR:Script registering but ScriptName npc_felhound_minion is not assigned in database. Script will not be used.
UPDATE creature_template SET ScriptName="npc_felhound_minion" WHERE entry=10656;
-- ERROR:Script registering but ScriptName boss_mother_smolderweb is not assigned in database. Script will not be used.
UPDATE creature_template SET ScriptName="boss_mother_smolderweb" WHERE entry=10596;
-- ERROR:Script registering but ScriptName boss_sneed_shredder is not assigned in database. Script will not be used.
UPDATE creature_template SET ScriptName="boss_sneed_shredder" WHERE entry=642;
-- ERROR:Script registering but ScriptName boss_sneed is not assigned in database. Script will not be used.
UPDATE creature_template SET ScriptName="boss_sneed" WHERE entry=643;
-- ERROR:Script registering but ScriptName boss_azshir_the_sleepless is not assigned in database. Script will not be used.
UPDATE creature_template SET ScriptName="boss_azshir_the_sleepless" WHERE entry=6490;
-- ERROR:Script registering but ScriptName boss_kormok is not assigned in database. Script will not be used.
UPDATE creature_template SET ScriptName="boss_kormok" WHERE entry=16118;
-- ERROR:Script registering but ScriptName boss_lord_blackwood is not assigned in database. Script will not be used.
UPDATE creature_template SET ScriptName="boss_lord_blackwood" WHERE entry=14695;
-- ERROR:Script registering but ScriptName mob_arugal_voidwalker is not assigned in database. Script will not be used.
UPDATE creature_template SET ScriptName="mob_arugal_voidwalker" WHERE entry=4627;
-- ERROR:Script registering but ScriptName boss_arugal is not assigned in database. Script will not be used.
UPDATE creature_template SET ScriptName="boss_arugal" WHERE entry=4275;
-- ERROR:Script registering but ScriptName mobs_rat_pestifere is not assigned in database. Script will not be used.
UPDATE creature_template SET ScriptName="mobs_rat_pestifere" WHERE entry=10441;
-- ERROR:Script registering but ScriptName boss_grilek is not assigned in database. Script will not be used.
UPDATE creature_template SET ScriptName="boss_grilek" WHERE entry=15082;
-- ERROR:Script registering but ScriptName boss_hazzarah is not assigned in database. Script will not be used.
UPDATE creature_template SET ScriptName="boss_hazzarah" WHERE entry=15083;
-- ERROR:Script registering but ScriptName mob_vilebranche is not assigned in database. Script will not be used.
UPDATE creature_template SET ScriptName="mob_vilebranche" WHERE entry=11391;
-- ERROR:Script registering but ScriptName boss_wushoolay is not assigned in database. Script will not be used.
UPDATE creature_template SET ScriptName="boss_wushoolay" WHERE entry=15085;
-- ERROR:Script registering but ScriptName npc_gurubashi_axethrower is not assigned in database. Script will not be used.
UPDATE creature_template SET ScriptName="npc_gurubashi_axethrower" WHERE entry=11350;
-- ERROR:Script registering but ScriptName npc_fils_hakkar is not assigned in database. Script will not be used.
UPDATE creature_template SET ScriptName="npc_fils_hakkar" WHERE entry=11357;
-- ERROR:Script registering but ScriptName boss_lady_faltheress is not assigned in database. Script will not be used.
UPDATE creature_template SET ScriptName="boss_lady_faltheress" WHERE entry=14686;
-- ERROR:Script registering but ScriptName boss_yeggeth is not assigned in database. Script will not be used.
UPDATE creature_template SET ScriptName="boss_yeggeth" WHERE entry=15386;
-- ERROR:Script registering but ScriptName npc_sandstalker is not assigned in database. Script will not be used.
UPDATE creature_template SET ScriptName="npc_sandstalker" WHERE entry=15323;
-- ERROR:Script registering but ScriptName npc_neeru_fireblade is not assigned in database. Script will not be used.
UPDATE creature_template SET ScriptName="npc_neeru_fireblade" WHERE entry=3216;
-- ERROR:Script registering but ScriptName npc_cenarion_scout_azenel is not assigned in database. Script will not be used.
UPDATE creature_template SET ScriptName="npc_cenarion_scout_azenel" WHERE entry=15610;
-- ERROR:Script registering but ScriptName npc_Krug_SkullSplit is not assigned in database. Script will not be used.
UPDATE creature_template SET ScriptName="npc_Krug_SkullSplit" WHERE entry=15612;
-- ERROR:Script registering but ScriptName mob_HiveRegal_HunterKiller is not assigned in database. Script will not be used.
UPDATE creature_template SET ScriptName="mob_HiveRegal_HunterKiller" WHERE entry=15620;
-- ERROR:Script registering but ScriptName npc_Merok is not assigned in database. Script will not be used.
UPDATE creature_template SET ScriptName="npc_Merok" WHERE entry=15613;
-- ERROR:Script registering but ScriptName npc_Shai is not assigned in database. Script will not be used.
UPDATE creature_template SET ScriptName="npc_Shai" WHERE entry=15615;

```

**Comment by StadenElysium** [comment]
The database released is the correct one. I don't have the history though, so I can't see exactly when the errors were introduced.

**Comment by iNDRLM** [comment]
The DB released isnt the correct one, its a stock mangos, it is evident with all the errors that are present, there is no way that would be used in production..
I dont know how you could even suggest otherwise.

**Comment by iNDRLM** [comment]
Thanks for adding these brotalnia

**Comment by PlaskED** [comment]
The DB is not stock mangos. Atleast not the one in release.

**Comment by PlaskED** [comment]
As for the scripts, i noticed some have both cpp files but also have entries in creature_ai_scripts so the reason cpp isnt used might be because they moved AI to DB.

**Comment by Kittnz** [comment]
@iNDRLM This isn't a stock mangos db.. If you have played on nostalrius or elysium you will know. You can see differences. Anyway, the reason of the script errors are because of c++ script removal. In the leak there are several scripts that are no longer included in the official release. I'm sorry elysium dev's but no commit history at all? Thats just plain weird. Either delete the scripts from npc in the database or add c++ scripts. Eitherway they can be found in the leak.

**Comment by Kittnz** [comment]
Why isn't this merged yet?

**Pull request merged**
