### PR TITLE
Sunder Armor, Bloodthirst, Execute, and Shield Slam Trigger Main Hand

### PR DESCRIPTION
**Pull request by Yoshgit**
Addressing issues #1011 #1012 #1021 #1023

### CODE REVIEW

**Comment by brotalnia** [comment]
You need to replace the tabs with 4 spaces.

**Comment by Yoshgit** [comment]
Good to know, first time trying to contribute. Tabs were out of habit.

**Comment by m-laniakea** [comment]
These Execute and Shield Slam changes have been denied previously by our QA team.
https://github.com/elysium-project/server/pull/187

**Comment by Yoshgit** [comment]
My recent posts in issues should prove that, at the very least, execute should be triggering main hand procs. Shield slam, on the other hand, should be consistent with shield bash.

**Comment by Yoshgit** [comment]
If shield slam triggering main hand procs is an issue with the QA team, I can remove that check, but if that is the case I also feel like it makes sense to remove shield bash as well.

**Comment by GuybrushGit** [comment]
Should probably use class masks checks instead of spell ids.

**Comment by Zarant** [comment]
Your proposed fix won't work with sunder armor.

The lines of code you changed only gets processed if the spell does some kind of damage 
(around line 1176).

**Comment by m-laniakea** [comment]
Verdict from QA: 
Sunder Armor, etc. triggering main hand procs is a bug.

**Comment by Yoshgit** [comment]
I don't understand how the QA team could possibly deny this? I went as far as to find video evidence of them triggering on live servers?

**Comment by Yoshgit** [comment]
7:12 https://www.youtube.com/watch?v=hGewOCCa1_A
1:42 https://www.youtube.com/watch?v=A6JcHwaaphg
4:15 https://www.youtube.com/watch?v=hGewOCCa1_A
5:37 https://www.youtube.com/watch?v=hGewOCCa1_A
6:06 https://www.youtube.com/watch?v=hGewOCCa1_A
6:42 https://www.youtube.com/watch?v=hGewOCCa1_A
9:33 https://www.youtube.com/watch?v=WMlJWC0Glqw&t
Still frame evidence for execute [http://imgur.com/a/Wl7Gf](url)

**Comment by m-laniakea** [comment]
QA is not denying it happened in vanilla, but rather recognizes it as a bug that was on the to-squash list.

**Pull request closed without merging**
