### PR TITLE
Fix to Ignite dot damage

### PR DESCRIPTION
**Pull request by GuybrushGit**
This fixes the caster and target modifiers from being applied to the ignite dot damage.

Another issue related to ignite is the partial resist rate, see my first comment here: https://github.com/elysium-project/server/issues/534
In the video posted there the ignite resists twice in a short amount of time, let me know if you consider this enough to make ignite follow normal resist rules and I'll add it to this PR as well.

### CODE REVIEW

**Comment by thepparker** [comment]
The only issue I can see with this is that the ignite damage won't be increased by the stack amount anymore. We'll have to multiply it by the stacks manually on trigger. 

Something like 

`tickDamage = tickDamage / (2 * igniteAura->GetStackAmount());` when calculating the rollover damage
and then
`tickDamage *= igniteHolder->GetStackAmount();` after we mod the stack amount.

In testing ignite ticks seem to resist often enough, including 2-3 partial resists in a row, so I'm not sure about changing its classification.

**Comment by GuybrushGit** [comment]
@thepparker I don't think I understand, my change only prevents outside modifiers from being applied. I don't see how it affects the damage being incremented on each tick here: 
https://github.com/elysium-project/server/blob/400cb2d64ed0c1c0598ce0867314d38e47fb2103/src/game/UnitAuraProcHandler.cpp#L738

**Comment by thepparker** [comment]
Ignite damage not only rolls over, but because it is a stacking ability, the damage is multiplied by the stack which is handled in Unit::SpellDamageBonusDone (https://github.com/GuybrushGit/server/blob/0e73e401cba55c6131a1161eeb2ddd2470d72510/src/game/Objects/Unit.cpp#L6260). If we don't multiply the stack, ignite is only ever ticking for the rollover damage which usually ends up around 700.

**Comment by thepparker** [comment]
Actually, it appears that the stack damage is handled in SpellAuraHolder::SetStackAmount. The stack handling in Bonus* is just for that, the bonus addition. With your changes I can't get ignites above around 1.5k with 1000 spellpower, so something is off. I think the stack application is broken since it is using the prototype base damage rather than our modified damage, and the bug was hidden due to other factors. I'm going to fiddle around with it some more.

**Comment by GuybrushGit** [comment]
This is with my patch, using a spell that always does 750 (felfire): 
https://streamable.com/kxkix
Spamming a ton it caps out at 750 ticks (150*5): https://streamable.com/t6elx
This is the intended behaviour right?

The only possible issue I found is the initial damage being carried, even if we use a low damage spell, see:
https://streamable.com/1f7td

Unless this is intended as well?

**Comment by thepparker** [comment]
The low damage crit keeping ignite up is intended, any fire crit will maintain the ignite. I agree, damage checks out. I was wrong about the stack multiplying, ignite is weird in that regard. Seems all the stack is there for is to cap the roll. 

Preventing ignite from double scaling with caster mods is correct, that will stop it growing out of control when building stacks. However, I'm not sold on preventing damage taken mods from double dipping. https://youtu.be/bMWKNeIISmo?t=97 clearly demonstrates the damage jumping when CoE is applied. Whether the mod is taken into account on later ignite applications to prevent them doubling up is unknown, but I think it is a feature of ignite.

If we let damage taken mods double dip (say, 5 stack imp scorch and CoE), we get a 1.265 increase on the ignite which checks out. Nothing obscene like caster mod scaling.

Other than that, I'm happy.

**Comment by GuybrushGit** [comment]
Seems like a bug to double dip like that but its blizzlike, reverted that part.

**Comment by m-laniakea** [comment]
@GuybrushGit Ignite mechanics were confirmed working by Nano, including Level 1 fireballs keeping the tick damage going. It's just the interaction with spell damage mods increasing the tick damage, which caused the problems. Ignite damage should depend only on the fire crit amount, and your two lines in Unit.cpp should take care of that.

**Pull request merged**
