### PR TITLE
Fix build on Linux.

### PR DESCRIPTION
**Pull request by Anubisss**
Fixed and tested on:
```
Ubuntu 16.04.2 LTS x64
gcc version 5.4.0
cmake version 3.5.1
```

No idea about the ACE_HANDLE change breaks building on other platforms. IMO no.

### CODE REVIEW

**Comment by mewsian** [comment]
Fixed build for me on debian jessie 64-bit. Thanks!

**Comment by Locario** [comment]
i will try on debian, same problem in ubuntu, seems like i am doing something wrong, what? i don't know

**Comment by Locario** [comment]
root@ubuntu:/home/oscar/elysiumOS/server/src# cmake .. -DCMAKE_CXX_COMPILER=/usr/bin/g++-5 -DCMAKE_C_COMPILER=/usr/bin/gcc-5
-- Detected 64-bit platform.
--
This script builds the MaNGOS server.
  Options that can be used in order to configure the process:
    PREFIX: Path where the server should be installed to
    PCH: Use precompiled headers
    DEBUG: Debug mode
  To set an option simply type -D<OPTION>=<VALUE> after 'cmake <srcs>'.
  For example: cmake .. -DDEBUG=1 -DPREFIX=/opt/mangos

-- Found ACE library: /usr/lib/libACE.so
-- Found ACE headers: /usr/include
-- Using mysql-config: /usr/bin/mysql_config
-- Found MySQL library: /usr/lib/x86_64-linux-gnu/libmysqlclient.so
-- Found MySQL headers: /usr/include/mysql
--
-- Core revision: a10772dbe9d061129f9d 2017-03-11 17:52:44 +0000
-- Install server to: /home/oscar/elysiumOS/server
--
-- Use PCH               : No
-- PGO profile           : Disabled
-- Memory allocation     : TBB/Release /usr/lib/x86_64-linux-gnu/libtbbmalloc.so;/usr/lib/x86_64-linux-gnu/libtbb.so
-- Detected compiler     : GNU
-- Build in debug-mode   : No  (default)
-- Use anticheat    : No  (default)
-- Build scripts    : Yes (default)
-- Debug symbols         : Disabled
-- Build flags (RELEASE) : -O3 -DNDEBUG  -std=c++14 --no-warnings -fexceptions -fnon-call-exceptions -march=native -mtune=native -pipe
-- Build flags (DEBUG)   : -g  -std=c++14 --no-warnings -fexceptions -fnon-call-exceptions -march=native -mtune=native -pipe
-- Configuring done
-- Generating done
-- Build files have been written to: /home/oscar/elysiumOS/server/src
root@ubuntu:/home/oscar/elysiumOS/server/src# make
[  8%] Built target g3dlite
[  8%] Built target gsoap
[  9%] Built target detour
[ 14%] Built target shared
[ 14%] Built target framework
Scanning dependencies of target realmd
[ 14%] Building CXX object src/realmd/CMakeFiles/realmd.dir/Main.cpp.o
[ 14%] Linking CXX executable realmd
[ 15%] Built target realmd
[ 15%] Building CXX object src/game/CMakeFiles/game.dir/AdvancedPlayerBotAI.cpp.o
In file included from /home/oscar/elysiumOS/server/src/game/AI/CreatureAI.h:28:0,
                 from /home/oscar/elysiumOS/server/src/game/AI/PlayerAI.h:28,
                 from /home/oscar/elysiumOS/server/src/game/PlayerBots/PlayerBotAI.h:4,
                 from /home/oscar/elysiumOS/server/src/game/AdvancedPlayerBotAI.h:13,
                 from /home/oscar/elysiumOS/server/src/game/AdvancedPlayerBotAI.cpp:11:
/home/oscar/elysiumOS/server/src/game/ObjectGuid.h:333:11: error: redefinition of ‘class std::hash<ObjectGuid>’
     class hash<ObjectGuid>
           ^
/home/oscar/elysiumOS/server/src/game/ObjectGuid.h:239:12: error: previous definition of ‘class std::hash<ObjectGuid>’
     struct hash<ObjectGuid>
            ^
src/game/CMakeFiles/game.dir/build.make:62: recipe for target 'src/game/CMakeFiles/game.dir/AdvancedPlayerBotAI.cpp.o' failed
make[2]: *** [src/game/CMakeFiles/game.dir/AdvancedPlayerBotAI.cpp.o] Error 1
CMakeFiles/Makefile2:560: recipe for target 'src/game/CMakeFiles/game.dir/all' failed
make[1]: *** [src/game/CMakeFiles/game.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by EinBaum** [comment]
I'm running gcc 4.9.2 and the hash function is required for my build to succeed. Here's my version: https://github.com/EinBaum/server/commit/1c0b6ea52dce9a73c9da3f3fe7b7760046dcb8c0

**Comment by Anubisss** [comment]
@EinBaum hmmm yea, then maybe we should check the version of the compiler too in the macro.

Like:
`#if __GNUC__ < 5`

**Comment by EinBaum** [comment]
@Anubisss Excellent idea. Do you want to make that patch or should I do it?

**Comment by Anubisss** [comment]
@EinBaum You can/should. :)

**Comment by EinBaum** [comment]
Done. This pull request should be closed as mine contains the improved code.

**Pull request closed without merging**
