### PR TITLE
BWL fixes

### PR DESCRIPTION
**Pull request by GuybrushGit**
Some of these issues are debatable, evidence is scarce:

- Added disarm immunity to Wyrmguards and Captains. It doesn't seem right that these mobs can be nullified by disarm but I found no evidence either way. No guides mention disarming.
- https://github.com/elysium-project/server/issues/3083 Death Talon Hatcher interrupt immunity.
- https://github.com/elysium-project/server/issues/3151 Flamestrike increased initial timer and removed random targetting
- https://github.com/elysium-project/server/issues/3082 Razorgore's cleave range
- Gave Death Talon Wyrmguard his proper weapon
- https://github.com/elysium-project/server/issues/2955 Overseer pack corrected positioning
- https://github.com/elysium-project/server/issues/3202 Fix to Nefarian warrior call

### CODE REVIEW

**Comment by ohganot** [comment]
If you change flamestrike to be not interruptible, you also need to make it only cast on the current aggro target. As you see in the videos posted in issue #3083 the flamestrikes are only cast on the tank.

**Comment by thepparker** [comment]
While I agree the Hatchers should probably be immune to interrupts, we need to change the casting logic for them if we're making them immune. For example, you can see in the videos that they do not begin to cast Flamestrike for a solid 10 seconds, however on our server they will begin casting immediately on the pull. I think it's a bit unfair for the mob to get a free cast while standing in the middle of the room, potentially aggroing additional mobs with it.

I'm not sold on the disarm immunity, perhaps the Wymguards (big ones?) and Captains should be, but it seems to make sense the smaller ones can be disarmed. There are a few cases where disarming mobs is not well documented in Vanilla, for example the Alterac Valley Marshals/Warmasters and Generals.

**Comment by Aklol** [comment]
I think the Razorgore cleave range was blizzlike. However, I don't think there's enough evidence to warrant the Hatcher change yet. If there's any change, it's that Flamestrike should be cast on the current target (typically tank).

**Comment by GuybrushGit** [comment]
Removed Overseer from the disarm list, increased flamestrike initial timer and removed random targetting (confirmed on multiple videos).

**Comment by Aklol** [comment]
If I'm reading the code correctly, the flamestrike target fix also applies to Spellbinders?

And we're holding off on the counterspell fix?

**Pull request closed without merging**
