### PR TITLE
Fix to Mind Control dispels

### PR DESCRIPTION
**Pull request by GuybrushGit**
Issue https://github.com/elysium-project/server/issues/2597
Also fixes dispelling the MC caster not interrupting the MC.

| Dispel behaviour after this commit  |  |
| ------------- | ------------- |
| Alliance dispel friendly Horde MC victim  | dispels debuffs |
| Alliance dispel friendly Alliance MC caster | dispels debuffs |
| Alliance dispel friendly NPC MC victim | dispels debuffs |
| Alliance dispel hostile Alliance MC victim | dispels MC first and then random buffs |
| Alliance dispel hostile Horde MC caster | dispels random buffs including MC |
| Alliance dispel hostile NPC MC victim (friendly to Alliance before the charm) | dispels MC first and then random buffs |
| Alliance dispel hostile NPC MC victim (hostile to Alliance before the charm) | dispels random buffs |

### CODE REVIEW

**Comment by ohganot** [comment]
Alliance dispel hostile Alliance MC victim | dispels MC first and then random buffs
-- | --

Does this mean that using Dispel Magic will dispel MC + 1 random buff? It should only dispel MC.

**Comment by GuybrushGit** [comment]
Would need concrete evidence of that. I saw posts saying 2 aura dispels will remove MC + a buff.

**Comment by ohganot** [comment]
Take a closer look at the videos posted in the bugreport. Both in the Lucifron video and the Orgrimmar video you can see that only the MC is getting dispelled.

Besides, Dispel Magic clearly states: "Dispels magic on the target, removing 2 harmful spells from a friend or 2 beneficial spells from an enemy."

It can do either one or the another. It can't dispel harmful and beneficial spells at the same time.

**Comment by GuybrushGit** [comment]
It makes sense but we can't tell which rank dispel magic they used.
This thread has multiple people saying it removes MC + 1 buff: http://www.mmo-champion.com/threads/647217-Dispel-Magic-on-mc-ed-targets

**Comment by ohganot** [comment]
Fair enough. As long as it can be countered by using Rank 1 Dispel Magic, which removes only 1 buff or debuff, its fine.

Also, if a Mind Control effect is dispellable, it should have Dispel Type: Magic associated with it. If not, it's n/a. 

http://db.vanillagaming.org/?spell=785 Prophet Skeram Mind Control isn't dispellable.
http://db.vanillagaming.org/?spell=22667 Nefarian Mind Control isn't dispellable.
http://db.vanillagaming.org/?spell=20740 Lucifron Mind Control is dispellable.

**Comment by GuybrushGit** [comment]
That's not an issue, non-dispellables with continue not dispellable.

Just added a fix to Dispel / Devour Magic never resisting when removing buffs.

**Comment by GuybrushGit** [comment]
A previous fix to farsight spells was causing MC to never resist. 
Reverted it and fixed farsight properly: now it can resist but won't agro when it does.

**Pull request closed without merging**
