### PR TITLE
Apply diminishing returns to heartbeat timers

### PR DESCRIPTION
**Pull request by GuybrushGit**
Fixes https://github.com/elysium-project/server/issues/2089

Diminishing returns are being applied to spell durations but not heartbeat durations, so for example a long CC like Polymorph will not be affected by DR:

> Polymorph is subject to diminishing returns. Duration displayed on the debuff is capped at 12 seconds against players, then 6 and 3 after subsequent casts
http://wowwiki.wikia.com/wiki/Polymorph?oldid=682060

TBC source but vanilla is the same with 15 sec cap, so it should be 15 -> 7.5 -> 3.75->0.
Currently in Elysium its 15 -> 15 -> 15 -> 0.

### CODE REVIEW

**Comment by cocely** [comment]
crash

Address   Frame     Function      SourceFile
000000013F8C783D  00000000BEE3E640  Unit::GetDiminishing+D  d:\elysium-project\core5\src\game\objects\unit.cpp line 8314
000000013FADD856  00000000BEE3E6F0  SpellAuraHolder::Update+56  d:\elysium-project\core5\src\game\spells\spellauras.cpp line 6265
000000013FB66A78  00000000BEE3E750  Spell::update+308  d:\elysium-project\core5\src\game\spells\spell.cpp line 3806
000000013FB5AC23  00000000BEE3E7A0  SpellEvent::Execute+33  d:\elysium-project\core5\src\game\spells\spell.cpp line 7448
000000013FDA5436  00000000BEE3E800  EventProcessor::Update+66  d:\elysium-project\core5\src\framework\utilities\eventprocessor.cpp line 58
000000013F8DB66D  00000000BEE3E870  Unit::Update+DD  d:\elysium-project\core5\src\game\objects\unit.cpp line 270
000000013F972128  00000000BEE3E900  Creature::Update+558  d:\elysium-project\core5\src\game\objects\creature.cpp line 733
000000013F956B2A  00000000BEE3E980  MaNGOS::ObjectUpdater::Visit+24A  d:\elysium-project\core5\src\game\maps\gridnotifiersimpl.h line 55
000000013F9555A9  00000000BEE3E9F0  Map::UpdateActiveCellsCallback+1E9  d:\elysium-project\core5\src\game\maps\map.cpp line 644
000000013F9552F5  00000000BEE3EAB0  Map::UpdateActiveCellsAsynch+6C5  d:\elysium-project\core5\src\game\maps\map.cpp line 697
000000013F955909  00000000BEE3EB50  Map::UpdateCells+A9  d:\elysium-project\core5\src\game\maps\map.cpp line 760
000000013F954045  00000000BEE3FD90  Map::Update+285  d:\elysium-project\core5\src\game\maps\map.cpp line 893
000000013FA4ABA1  00000000BEE3FDC0  ContinentAsyncUpdater::run+21  d:\elysium-project\core5\src\game\maps\mapmanager.cpp line 288
000000013FD9BC81  00000000BEE3FE00  ACE_Based::Thread::ThreadTask+71  d:\elysium-project\core5\src\shared\threading.cpp line 200

**Comment by thepparker** [comment]
Was this during personal usage or random activity? If you could describe what happened it would be very helpful. I have a feeling I know what the cause is but it's being a little iffy to reproduce right now

**Comment by cocely** [comment]
[mangosd.exe_[4-9_14-25-21].txt](https://github.com/elysium-project/server/files/1274202/mangosd.exe_.4-9_14-25-21.txt)

I don't know how it happened

**Comment by thepparker** [comment]
What's the latest commit you are using?

**Pull request merged**
