### PR TITLE
Fix to unlootable quest item containers

### PR DESCRIPTION
**Pull request by GuybrushGit**
Fixes quest item containers not being lootable in quests like It's a Secret to Everybody (https://github.com/elysium-project/server/issues/1278) or Ferocitas the Dream Eater (https://github.com/elysium-project/server/issues/778).

Also added the missing Faded Photograph to the Linken pack: http://db.vanillagaming.org/?item=11108

### CODE REVIEW

**Comment by forpotu** [comment]
LOL HEY POTU!! I HOPE THERES NO BODY ON ELIYSUM WITH PERSON INFO ABOUT YOU OR SOCIAL MEDIA YOU BE SURPRISED HOW CRAZY SOME PEOPLE ARE IF THEY GET THAT INFO ON A FGT LIEK YOU

**Comment by Pisshead** [comment]
The problem just came up again.

**Comment by Pisshead** [comment]
With: It's a secret to everybody. The backpack is not lootable

**Comment by Pisshead** [comment]
ok I found out: Exitting the game and relogging isn't the same... If you relogg by pressing esc ingame and press log out and THEN relogg it works

**Pull request closed without merging**
