### PR TITLE
Fixes to Six Demon Bag

### PR DESCRIPTION
**Pull request by GuybrushGit**
Fixes https://github.com/elysium-project/server/issues/1025

Changed Fireball and Polymorph spells.
Fixed Felhound AI and stats with data from the bestiary.

### CODE REVIEW

**Comment by binary909** [comment]
Amazing

**Comment by Mostprovidedlinks** [comment]
Fix needed

Not instant cast frost bolt still happening and sheep is still sheeping me and not opponent

**Comment by Mostprovidedlinks** [comment]
@GuybrushGit  two fixes needed

Not instant cast frost bolt still happening and sheep is still sheeping me and not opponent

Please can you fix the frostbolt guybrushgit ty

**Comment by GuybrushGit** [comment]
Fixed delay.

**Comment by Mostprovidedlinks** [comment]
@GuybrushGit  delay for frostbolt is still not fixed

**Comment by Mostprovidedlinks** [comment]
@GuybrushGit felhound minion is also hitting way too low as a level 60. Its hitting for 9 damage
https://youtu.be/wnGCTfPDdH4

**Comment by GuybrushGit** [comment]
This hasn't even been merged yet.

**Comment by Itembugs** [comment]
polymorph still not working, only affects user

**Comment by binary909** [comment]
@Itembugs  

You didn't even bother to read his comment before posting, it has not been merged with the live server yet.

**Pull request merged**
