### PR TITLE
Misc DB fixes

### PR DESCRIPTION
**Pull request by GuybrushGit**
**NPC**

- https://github.com/elysium-project/server/issues/2025 Deleted extra Jed Runewatcher pool
- https://github.com/elysium-project/server/issues/1891 Removed flee AI, confirmed with video http://www.youtube.com/watch?v=1KdPk6Jj3vk&t=4m45s
- https://github.com/elysium-project/server/issues/1877 Slightly moved Syndicate Spy out of Gol'dir's range
- https://github.com/elysium-project/server/issues/1439 Added Namdo Bizzfizzle to Gnomer 
- https://github.com/elysium-project/server/issues/2250 Meshlok the Harvester rank
- https://github.com/elysium-project/server/issues/1897 Wrathtail Sea Witch and Felslayer mana burn spell
- https://github.com/elysium-project/server/issues/1949 Pao'ka Swiftmountain escort status
- https://github.com/elysium-project/server/issues/2285 Oozes creature type
- https://github.com/elysium-project/server/issues/2311 Cliff Lurker damage level and hp
- https://github.com/elysium-project/server/issues/2342 Araj the Summoner rank
- https://redd.it/6x8xrb SM Graveyard: Improved the spawn rates on the GY rare spawns from 5% to 15%, every other rare spawn is at 15% don't know why these were set so low.
 
**Quest**

- https://github.com/elysium-project/server/issues/1870 The Darkreaver Menace level requirement
- https://github.com/elysium-project/server/issues/1821 Call of Water typo
- https://github.com/elysium-project/server/issues/1143 Bring the Light buffs fortitude on quest complete
- https://github.com/elysium-project/server/issues/1849 Desperate Prayer method fix
- https://github.com/elysium-project/server/issues/2274 Ungoro Quests level requirements
- https://github.com/elysium-project/server/issues/2262 Proof of Deed text
- https://github.com/elysium-project/server/issues/1884 Strange Water Globe not repeatable
- https://github.com/elysium-project/server/issues/1926 Glyphic Scroll text
- https://github.com/elysium-project/server/issues/2047 Nat Pagle quests level requirement
- https://github.com/elysium-project/server/issues/2213 Stone Watcher increased despawn timer for the people who actually read the lore
- https://github.com/elysium-project/server/issues/2313 Gaxim Rustfizzle quest chain requirements

**Mechanics**

- https://github.com/elysium-project/server/issues/2038 Fixed Execute log event
- https://github.com/elysium-project/server/issues/1907 Crystal of Zin-malor now remains after death and shows up as a buff (dont bother reading the comments on 1907 waste of time)
- https://github.com/elysium-project/server/issues/1147 Annihilator / Rivenspike / Bashguuder proc rates: Couldn't find any proper research but its clear the current 1ppm is too low, changed both to 5ppm which is roughly 15%.

**Objects**

- https://github.com/elysium-project/server/issues/1345 Deleted unreachable node
- https://github.com/elysium-project/server/issues/1430 Dusty tome lootable in combat

**Items**

- https://github.com/elysium-project/server/issues/1154 https://github.com/elysium-project/server/issues/2327 Set Gorosh to always drop an item (currently only drops 15% of the time)
- https://github.com/elysium-project/server/issues/763 Imperial Qiraji Regalia/Armaments: removed extra loot template and fixed drop rates
- https://github.com/elysium-project/server/issues/2318 Removed Mark of Hakkar from Lockbox

### CODE REVIEW

**Comment by Dasharius** [comment]
Just a question:
Bashguuder got the same proc as Rivenspike. Does it has such a low procrate too?

**Comment by Dasharius** [comment]
Okay I maybe have another "problem". I tested bashguuder on our own Elysium coded server (preNaxxPTR).

I hit a training puppet and sometimes the debuff fell from 2 or 3 stacks back down to 1 stack without reaching 30 seconds (http://db.vanillagaming.org/?spell=17315) nor applying a new stack.

It happened 2 times:
1.
17:08:58 Puncture Armor
17:08:59 Puncture Armor (2)
Around 17:08:15 it went down to 1 Stack without a Message in the combat log.

2.
16:57:53 Puncture Armor (2)
16:58:03 Puncture Armor (3)
Around 16:58:06 It went down to 1 Stack without a Message in the combat log.

http://imgur.com/a/IjvcQ

If I should open a new Issue please say so :)

**Comment by theloras** [comment]
@GuybrushGit - could you also take a look at the proc rate for Heart of Wyrmthalak please?

I don't have the trinket myself but a few Paladins on Anathema have told me that it's proc rate is abysmally low in a similar fashion as Darkmoon Card: Maelstrom used to be before I got the devs to fix it:

Darkmoon Card: Maelstrom proc rate is abysmal on Elysium - RESOLVED
https://elysium-project.org/bugtracker/issue/820

**Comment by GuybrushGit** [comment]
@Dasharius can't reproduce. Don't make issues that only happen on your modified server.

@theloras make an issue for it. With some sort of evidence.

**Comment by Dasharius** [comment]
@GuybrushGit I will try to test it on darrowshire or Naxx PTR then. But as far as I know our server is completely unmodified. I didn't even modify the procrate. I created a gearset with 3% haste and 27% hit to even get the chance to reach 2 or 3 stacks with luck. I made this with the intention to help and not to create false assumptions. So please don't create false assumptions too with stating that our server is modified.

**Comment by Mostprovidedlinks** [comment]
@guybrushgit please add in the misc that the items damag and drain remain thesame when ressurecting without switching the trinket thanks
https://m.youtube.com/watch?v=kBtSAjKmPPw

**Comment by Mostprovidedlinks** [comment]
@GuybrushGit please add in the misc that the crystal of zin malors daamge and mana drain remain thesame when ressurecting without switching the trinket thanks
https://m.youtube.com/watch?v=kBtSAjKmPPw

**Comment by Mostprovidedlinks** [comment]
@GuybrushGit please add in the misc that the crystal of zin malors damage and mana drain remain thesame when ressurecting without switching the trinket thanks
https://m.youtube.com/watch?v=kBtSAjKmPPw

**Comment by Mostprovidedlinks** [comment]
@GuybrushGit please add in the misc that the crystal of zin malors damage and mana drain remain thesame when ressurecting when youbdont reequip the trinket thanks
https://m.youtube.com/watch?v=kBtSAjKmPPw

**Comment by Mostprovidedlinks** [comment]
@GuybrushGit you forgot to add in the misc that the crystal of zin malors damage and mana drain remain thesame when ressurecting when you dont reequip the item. Please add it thanks 
https://m.youtube.com/watch?v=kBtSAjKmPPw

**Comment by Aklol** [comment]
Hey Guybrush, thanks for the fixes. When can we expect these changes to go live?

**Pull request merged**
