### PR TITLE
Scripted Gurubashi Arena Event

### PR DESCRIPTION
**Pull request by brotalnia**
Fixes issue - https://github.com/elysium-project/server/issues/922

There were 3 separate game events added for the same thing, and none of them worked properly. This should fix it. Every 3 hours starting from midnight Short John Mithril will announce to the zone that he has a treasure to give, then will walk to the center of the arena and spawn the chest.

### CODE REVIEW

**Comment by sipertruk** [comment]
The gob is only going in at walk speed the first time.

**Comment by brotalnia** [comment]
As he should.
https://www.youtube.com/watch?v=vyw4RCMjuHk
https://www.youtube.com/watch?v=b5l5Pju2cMg
https://www.youtube.com/watch?v=DOCLnTvkXQI
https://www.youtube.com/watch?v=Q-pZuf75WEI

**Comment by sipertruk** [comment]
I mean, I tested your script while doing ffa fixes, and noticed that starting at the second occurrence of the event he's in run mode while he should walk to the center,

**Comment by brotalnia** [comment]
I get what you mean now, I'll fix it tomorrow.

**Pull request merged**
