### PR TITLE
 Blasted Lands buffs stats and stacking rules.

### PR DESCRIPTION
**Pull request by GuybrushGit**
- https://github.com/elysium-project/server/issues/2242 Implemented the +50 stats pre-1.11, had to hardcode it since Blizzard just modified the spell. The client will still display 25 but players will get 50.

 - https://github.com/elysium-project/server/issues/2197 Fixed the stacking rules. New rules are: only 1 zanza buff allowed, only 1 BL buff allowed and only 1 between Spirit of Zanza / BL Stamina / BL Spirit allowed.

### CODE REVIEW

**Comment by brotalnia** [comment]
I thought we aren't doing spell progression cause the spells look wrong in the client? If we want that, i could make it so spells are loaded from the db and it will load the table for the appropriate patch, giving you full patch by patch spell progression with all the old effects, base points and other changes listed in the patch notes, without needing to hardcore things like this.

**Comment by GuybrushGit** [comment]
Yeah its debatable, its a spell change but its still related to itemization. Should I remove that part and just leave the stacking fix?

**Comment by brotalnia** [comment]
Yes i feel it's best to take it out. If we want it changed on live realms, it should be done in spell_effect_mod instead of hardcoding the basepoints in the core. There's a custom sql folder now -> https://github.com/elysium-project/server/tree/development/sql/custom

**Comment by thepparker** [comment]
Leave the stats as they are in 1.12, stacking looks okay.

**Comment by GuybrushGit** [comment]
Reverted

**Pull request merged**
