### PR TITLE
Prevent proc spells from breaking CC

### PR DESCRIPTION
**Pull request by GuybrushGit**
Fixes https://github.com/elysium-project/server/issues/2149

> The fire damage from the Blazefury Medallion and the Gutgore Ripper's effect should no longer immediately break Gouge.
> Stormshroud Set: The Lightning effect from this set will no longer break your Gouge.
> http://shadowpanther.net/roguechanges.htm

> Maelstrom will proc on a gouge but does not break the gouge.
> http://web.archive.org/web/20070515083410/http://www.thottbot.com/i19289

Seems like the default behaviour for these triggered proc spells is not to break the CC that triggered them.
Made it so spells caused by SPELL_AURA_PROC_TRIGGER_SPELL dont remove auras with SPELL_ATTR_EX_UNK18 (stun, polymorph, daze, sleep)

### CODE REVIEW

**Comment by thepparker** [comment]
I disagree. It seems pretty explicit to me that it should only be spells triggered by casting the CC that should not interrupt the CC immediately.

**Comment by GuybrushGit** [comment]
Yeah ideally you would want to check that, but it would mean that spells would have to store the spell that triggered the spell that triggered them. I can implement it that way if you think its fine.

**Comment by thepparker** [comment]
I think it's worth tracking the spell it was procced from, yea

**Comment by GuybrushGit** [comment]
Fixed it.

**Comment by Harkonnen13** [comment]
Sad, bud this issue still works on Elysium. The Lifesteal enchant proc breaks Gouge (not really often, but still), as well as the Darkmoon card: Maelstrom.

**Comment by ryancheung** [comment]
Is this fix live now or not?

**Pull request merged**
