### PR TITLE
Fixes to Seal of Righteousness

### PR DESCRIPTION
**Pull request by GuybrushGit**
Fixes the following:

https://github.com/elysium-project/server/issues/334
Made it so SoR ignores resistances

https://github.com/elysium-project/server/issues/332
https://github.com/elysium-project/server/issues/241
Made it so melee weapon modifiers like those talents apply to seals.

Also fixed a couple of other issues I noticed:

- Improved SoR talent was applying to judgement but not the seals.
- Bonuses from target debuffs were being applied twice (for ex. SoR currently gets twice the damage bonus from Judgement of the Crusader)

### CODE REVIEW

**Comment by QAkvastskaft** [comment]
Really nice fixes :+1:

**Comment by killerduki** [comment]
Hello guys , Bonuses from target debuff Judgement of the Crusader is meant to give twice the damage bonus, here is Evidence for that : 

https://www.youtube.com/watch?v=9DymPtTBzB4
Uploaded on Jun 12, 2006

You can see that at level 9 he is using 2.20 Weap speed , which leads to 2-3 damage out of maximum 4 damage by his Seal of Righteousness Rank 1.

Target have applied Judgement of the Crusader rank 1 (which increases you 20 holy dmg)

Apparently you can see as evidence that Judgement of the Crusader increased his Damage up to 6-7 which is pure evidence that Judgement of the Crusader should benefit twice , (in this case 4 damage the target increased) and Seal of Righteousness is doing 6-7 instead 2-3.

**Comment by killerduki** [comment]
Just to let you know , Judgement of the Crusader should benefit 20% Coefficient to Seal of Righteousness instead of 10% like Spell Damage , proven in this Video . 

Judgement of the Crusader is Holy Damage , not spell damage. 

Seal of Command is another Seal who should also benefit higher from Holy Damage.
Seal of Righteousness shown in Video as evidence should benefit 20% from Holy Damage.

**Comment by killerduki** [comment]
Improved SoR talent was applying to judgement but not the seals. 

 (I hope you didn't make it scale with spell dmg because that is TBC 2.1.0 Patch)

**Comment by killerduki** [comment]
Please reverse the 2 mention false fixes , because they will be gamebreaking to prot paladin , proven with evidence.

**Comment by Phoosy** [comment]
@killerduki Please stop making multiple posts in an issue when you can condense them down into one or edit your existing one. There is absolutely no reason you need to be making multiple posts in a row.

**Comment by theloras** [comment]
WoW BlueTracker
Poster: Flibble at 6/27/2006 5:50:31 PM PDT
Subject: Common Paladin Topics: Read This First Please

"Seal of Righteousness works best with faster weapons, and has a spell damage coefficient of 0.2. Weapon DPS and procs are therefore largely irrelevant."

http://blue.cardplace.com/cache/wow-paladin/1126317.htm

**Comment by GuybrushGit** [comment]
Fixed Improved SoR being applied after spell damage, now it affects only base damage.

Concerning the comments above:

The fix to target debuffs being applied twice should not be reverted. It was a bug causing the SpellDamageBonusTaken function to run twice, not a feature.

There seems to be some disagreement concerning the spell power coefficient of SoR, probably due to how many changes this spell went through:

- Killerduki claims that regular spell power gives 10% and holy spell power gives 20% and posted some video evidence above. The video evidence is not the best since it doesn't show the damage without the debuff and the numbers are so small it could be explained by how the math is rounded. Different schools of magic having different coefficients is an unprecented mechanic, I don't think any spell in the game works like that atm.

- Theloras linked a post that says its 20%: http://blue.cardplace.com/cache/wow-paladin/1126317.htm

- The 1.12 theorycrafting addon has it at 10% / 12% depending on weapon.

- Allahkazam has it at 9.2% * weapon speed or 10.8% * weapon speed: http://wow.allakhazam.com/wiki/spell_coefficient_(wow). This is the formula currently used by Elysium.

I'll leave it up to the team to decide if the coefficient needs changing or not.

**Comment by theloras** [comment]
@GuybrushGit - nice work on the fixes and I hear you about the conflicting information on SoR but thank you either way!

Quick question for you though, will the fix for https://github.com/elysium-project/server/issues/334 (Made it so SoR ignores resistances) also apply towards this bug as well in BWL?

Death Talon Wyrmguard, Death Talon Overseer and Chromaggus in BWL all have permanent -75% Holy spell school damage shield
https://elysium-project.org/bugtracker/issue/3247

Currently, only Seal of Command is able to do normal damage against these trash npcs and the boss Chromaggus - whereas Judgement of Command, Seal/Judgement of Righteousness and Consecration all suffer from -75% dmg from their permanent spell damage elemental shields.

**Comment by GuybrushGit** [comment]
No, Chromagg shield is still reducing SoR. Make a seperate issue for it on github don't clutter this one.

**Comment by theloras** [comment]
ok will do

**Comment by killerduki** [comment]
Hello there ,the reason i point on the Video is because you can see the player is level 9 , he use Rank 1 Seal of Righteousness which cap at 4 damage if you are using slowest 4.0 weapon speed .

Currently in the Video you can see the player weapon speed is 2.2 and his Judgement of the Crusader is doing 20% from the Holy damage buffed .

If Seal of Righteousness rank 1 is 1-4 damage depend on the weapon speed , then 2.2 weapon speed should never do highest damage from SoR . 

And the Spell coefficient is not working according to http://wow.allakhazam.com/wiki/spell_coefficient_(wow)
Because currently in server i use Flurry Axe which is 1.5 Speed , with 30 Spell damage it doesn't give me 4 or 5 damage , currently it gives me 3 damage only.

If it was working according to allakhazam then it would been : 1.5 * 9.5 = 13.8
13.8 * 0.3 = 4.14 (or let say 4 damage) which is not how it work in server.
Instead i do 22-23 without spell dmg with flurry axe and 25-26 with 30 spell dmg.

**Comment by GuybrushGit** [comment]
Just fixed an issue I found on the coeff calculation. 
It was using base attack speed instead of player attack speed when adding the bonus from Crusader.

**Comment by theloras** [comment]
@GuybrushGit - so it was taking unarmed swing speed of 2.0? instead of say 3.5 with ashkandi?

**Comment by killerduki** [comment]
Alright @GuybrushGit  i am really sorry for the confusion , you are correct , we just did some testing again.

It is my mistake ,  yeah the thing you said about attack speed seems was the issue , it is working as intended in server.

The reason why he does extra 4 Damage was because of his weapon 2.2

According to your allakhazam it match correctly where = 9.2x2.2 = 20.24 = 4 dmg from 20 Holy dmg.

I apologize and you are correct , the issue seems it was to base attack instead weap speed.

I gladly thank you for the issue you solved <3

**Comment by Mithedhel** [comment]
Can we also fix the fact that the damage dealt when you have seal of righteousness active often doesn't show at al in floating combat text?

**Pull request merged**
